spring:
    profiles:
        active: local
        group:
          test:
              - test
    application:
        name: deal
    datasource:
        url: jdbc:postgresql://localhost:5432/dbdeal
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
    liquibase:
      change-log: db.changelog/changelog.xml

    kafka:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: core.util.EmailMessageSerializer

server:
    port: 8082

calculator:
    offers-url: http://localhost:8080/calculator/offers
