name: SonarCloud

on:
#  workflow_dispatch: # Ручной запуск workflow
  push:
    branches:
      - "devops"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build core module
        working-directory: ./core
        run: mvn clean install

      - name: Analyze with SonarCloud core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: core
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_core \
            -Dsonar.projectName=core \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: calculator
        run: |
          mvn clean compile \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_calculator \
            -Dsonar.projectName=calculator \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud statement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: statement
        run: |
          mvn clean compile \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_statement \
            -Dsonar.projectName=statement \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud gateway
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: gateway
        run: |
          mvn clean compile \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_gateway \
            -Dsonar.projectName=gateway \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud deal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: deal
        run: |
          mvn clean test -Dtest=!DealApplicationTests \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_deal \
            -Dsonar.projectName=deal \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud dossier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: dossier
        run: |
          mvn clean test -Dtest=!DossierApplicationTests -Dsurefire.failIfNoSpecifiedTests=false \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_dossier \
            -Dsonar.projectName=dossier \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
