name: SonarCloud

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

on:
#  workflow_dispatch: # Ручной запуск workflow
  push:
    branches:
      - "devops"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build core module
        working-directory: ./core
        run: mvn clean install

      - name: Analyze with SonarCloud core
        working-directory: core
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_core \
            -Dsonar.projectName=core \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Analyze with SonarCloud calculator
        working-directory: calculator
        run: |
          mvn clean verify \
            jacoco:report \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_calculator \
            -Dsonar.projectName=calculator \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Upload CodeCov Report for calculator
        uses: codecov/codecov-action@v5
        with:
          files: calculator/target/site/jacoco/jacoco.xml
          flags: calculator
          fail_ci_if_error: true
          token: ${CODECOV_TOKEN}
          slug: dpnevsky/java-development

      - name: Analyze with SonarCloud statement
        working-directory: statement
        run: |
          mvn clean verify \
            jacoco:report \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_statement \
            -Dsonar.projectName=statement \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Upload CodeCov Report for statement
        uses: codecov/codecov-action@v5
        with:
          files: statement/target/site/jacoco/jacoco.xml
          flags: statement
          fail_ci_if_error: true
          token: ${CODECOV_TOKEN}
          slug: dpnevsky/java-development

      - name: Analyze with SonarCloud gateway
        working-directory: gateway
        run: |
          mvn clean verify \
            jacoco:report \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_gateway \
            -Dsonar.projectName=gateway \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Upload CodeCov Report for gateway
        uses: codecov/codecov-action@v5
        with:
          files: gateway/target/site/jacoco/jacoco.xml
          flags: gateway
          fail_ci_if_error: true
          token: ${CODECOV_TOKEN}
          slug: dpnevsky/java-development

      - name: Analyze with SonarCloud deal
        working-directory: deal
        run: |
          mvn clean test -Dtest=!DealApplicationTests \
            jacoco:report \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_deal \
            -Dsonar.projectName=deal \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Upload CodeCov Report for deal
        uses: codecov/codecov-action@v5
        with:
          files: deal/target/site/jacoco/jacoco.xml
          flags: deal
          fail_ci_if_error: true
          token: ${CODECOV_TOKEN}
          slug: dpnevsky/java-development

      - name: Analyze with SonarCloud dossier
        working-directory: dossier
        run: |
          mvn clean test -Dtest=!DossierApplicationTests -Dsurefire.failIfNoSpecifiedTests=false \
            jacoco:report \
            -B verify sonar:sonar \
            -Dsonar.projectKey=dpnevsky_dossier \
            -Dsonar.projectName=dossier \
            -Dsonar.organization=dpnevsky \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Upload CodeCov Report for dossier
        uses: codecov/codecov-action@v5
        with:
          files: dossier/target/site/jacoco/jacoco.xml
          flags: dossier
          fail_ci_if_error: true
          token: ${CODECOV_TOKEN}
          slug: dpnevsky/java-development
